name: Deploy (build & upload)
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Build
        run: |
          set -e
          npm ci || npm install
          npm run build
      - name: Upload dist to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "${{ vars.APP_DIR }}/dist"
          strip_components: 1
      - name: Finalize on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            APP_DIR="${{ vars.APP_DIR }}"
            mkdir -p "$APP_DIR/dist"
            echo "🚀 Déploiement terminé."
