name: Deploy to VPS
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (web+api)
        run: |
          npm ci
          npm run build
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            APP_DIR=/home/adminio/htdocs/cvrum.nrinfra
            pm2 stop cvrum-web || true
            cd $APP_DIR
            git fetch origin main
            git reset --hard origin/main
            npm ci
            npm run build
            pm2 start process.json
            pm2 save
